---
language: go

go:
  - 1.18
  - 1.17.8
  - 1.16.15
  - 1.15.15

sudo : false

notifications:
  irc:
    channels:
      - "irc.pl0rt.org#sp0rklf"
    skip_join: true

script:
  - if [ "$TRAVIS_REPO_SLUG" != "fluffle/goirc" ] ; then ln -s "$HOME/gopath/src/github.com/$TRAVIS_REPO_SLUG" /home/travis/gopath/src/github.com/fluffle/goirc ; fi
  - go test -v ./...
